#!/bin/bash
echo -e "Getting ESP Chip Info...\n"
echo -e "Base MAC Address:"
esptool.py --port $ESPPORT --baud $ESPBAUD --chip auto read_mac
echo -e "\nChip ID:"
esptool.py --port $ESPPORT --baud $ESPBAUD --chip auto chip_id
echo -e "\nFlash Status:"
esptool.py --port $ESPPORT --baud $ESPBAUD --chip auto read_flash_status
echo -e "\nSecurity Info:"
esptool.py --port $ESPPORT --baud $ESPBAUD --chip auto get_security_info
echo -e "\nEfuse Table:"
idf.py --port $ESPPORT --baud $ESPBAUD efuse-dump

echo -e "\nAll donsies~ :3\n"
