#!/bin/bash
echo -e "\nCleaning up Fully\n"

echo -e "\nRunning fullclean\n"

idf.py fullclean

if [ -d build ]; then
	echo -e "\nDeleting build dir\n"
	rm -rf build
else
	echo -e "\nNo build dir, skipping delete\n"
fi

if [ -f sdkconfig ]; then
	echo -e "\nDeleting sdkconfig\n"
	rm sdkconfig
else
	echo -e "\nNo sdkconfig, skipping delete\n"
fi

if [ -f *.old ]; then
	echo -e "\nDeleting *.old\n"
	rm *.old
else
	echo -e "\nNo *g.old, skipping delete\n"
fi

if [ -f *.bak ]; then
	echo -e "\nDeleting *.bak\n"
	rm *.bak
else
	echo -e "\nNo *.bak, skipping delete\n"
fi

echo -e "\nAll done :3\n"