#!/bin/bash
echo -e "\nCleaning up Fully\n"

echo -e "\nRunning fullclean\n"

if [ -d build ]; then
	echo -e "\nDeleting build dir\n"
	rm -rf build
fi

if [ -d managed_components ]; then
	echo -e "\nDeleting managed_components dir\n"
	rm -rf managed_components
fi

if [ -f sdkconfig ]; then
	echo -e "\nDeleting sdkconfig\n"
	rm -f sdkconfig
fi

if [ -f *.old ]; then
	echo -e "\nDeleting *.old\n"
	rm -f *.old
fi

if [ -f *.bak ]; then
	echo -e "\nDeleting *.bak\n"
	rm -f *.bak
fi

if [ -f dependencies.lock ]; then
	echo -e "\nDeleting dependencies.lock\n"
	rm -f dependencies.lock
fi

idf.py --preview fullclean

echo -e "\nAll done :3\n"