#!/bin/bash
echo -e "\nCleaning up Fully\n"

echo -e "\nRunning fullclean\n"

idf.py fullclean

if [ -d build ]; then
	echo -e "\nDeleting build dir\n"
	rm -rf build
else
	echo -e "\nNo build dir, skipping delete\n"
fi

if [ -f sdkconfig ]; then
	echo -e "\nDeleting sdkconfig\n"
	rm sdkconfig
else
	echo -e "\nNo sdkconfig, skipping delete\n"
fi

if [ -f sdkconfig.old ]; then
	echo "\nDeleting sdkconfig.old\n"
	rm sdkconfig.old
else
	echo -e "\nNo sdkconfig.old, skipping delete\n"
fi

echo "\nAll done :3\n"