#!/bin/bash
set -e # die on error

echo -e "Clean, build, flash, monitor in steps, dying on error"

# echo -e "\ncleaning up first\n"
# bash fullclean

echo -e "\nBuilding\n"
idf.py --preview build

echo -e "\nFlashing to $ESPPORT\n"
idf.py --preview flash

echo -e "\nMonitor time on $ESPPORT for target $ESPTARGET at $ESPBAUD\n"
idf.py --preview monitor

echo -e "\nAll done :3\n"