#!/bin/bash
set -e # die on error in theory

echo -e "Clean, build, flash, monitor in steps, dying on error"

echo -e "\ncleaning up first\n"
bash fullclean

echo -e "\nBuilding\n"
idf.py build

echo -e "\nFlashing to $ESPPORT\n"
idf.py flash

echo -e "\nMonitor time on $ESPPORT for target $ESPTARGET at $ESPBAUD\n"
idf.py monitor

echo -e "\nAll done :3\n"